try {
  cleanUp && cleanUp();
} catch (error) {
  console.log(error);
}
